### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by klaemo** [klaemo/docker-couchdb-ssl#12]
This image is outdated, has security issues and not maintained anymore. I would prefer to deprecate is so people don't install an unsupported CouchDB anymore.

@zemirco is this fine with you?

PS: I would be willing to transfer ownership with the condition that this image started using and up-to-date official CouchDB base image.

**Comment by zemirco** [comment]
Go for it.

**Comment by klaemo** [comment]
👍 Thanks
