### ISSUE TITLE
README should explain Stud is used, not CouchDB SSL

### ISSUE THREAD

**Issue by nickcmaynard** [klaemo/docker-couchdb-ssl#3]
Just wasted a /lot/ of time trying to get my certificate installed into CouchDB and wondering why I still got the self-signed one.

**Comment by klaemo** [comment]
It says so in the headline of the readme :D

**Comment by nickcmaynard** [comment]
.. yeah :(

I guess I'm new to this, so I had no idea what Stud was.  My assumption was that because CouchDB has SSL functionality, this docker image used that... despite the stud stuff.

Can I suggest something even clearer, for real idiots like me?

**Comment by klaemo** [comment]
Sure, if it helps you, it will definitely help other people as well. So go ahead :) I'm always open to be and inclusive as possible :)
