### ISSUE TITLE
Stud cannot verify client connections

### ISSUE THREAD

**Issue by mancvso** [klaemo/docker-couchdb-ssl#5]
Hi!
I stood upon your image to be able to expose a CouchDB instance on the public internet, allowing only trusted clients to connect to it.

Sadly, [https://github.com/bumptech/stud/issues/82] says it is not doable on stud. Any hint? (I'm quite new to CA/TLS/SSL/HTTPS)

Right now, TLS only protects the communication with CouchDB, but not the server from untrusted clients.

Thanks in advance.

**Comment by klaemo** [comment]
You might want to use a more capable SSL terminator in front of couchdb for that. nginx oder haproxy might be good options. They have reliable docker images as well :)
