### ISSUE TITLE
replace stud with nginx

### ISSUE THREAD

**Issue by zemirco** [klaemo/docker-couchdb-ssl#7]
Hey,

first of all thank you for the great work on docker couchdb and docker couchdb ssl! They are both great projects to get started quickly.

Are you interested (willing to accept pull requests) in replacing stud with nginx? [stud](https://github.com/bumptech/stud) is not actively maintained anymore and as far as I know does not support features like http2 (nginx already does). 

With the current setup it is not possible to sync between ios (using the couchbase lite framework) and CouchDB because iOS requires TLS 1.2. We could set `ssl = on` but that would also activate SSLv3. It is known to be [broken](http://disablessl3.com/).

I would even write some benchmarks to compare the current setup (with stud) to a setup with nginx.

**Comment by klaemo** [comment]
Hey Mirco,
thanks for you interest in this project. I agree that stud needs to be replaced. Although I'd suggest using haproxy instead of nginx. We don't need a full-fledged web server to do TLS termination. Additionally, CouchDB already uses haproxy for the upcoming 2.0. I think they made this decision, because nginx caused some problems, but I can't find the discussion anymore. I'd accept a PR replacing stud with haproxy. It doesn't have to be perfect, we can iterate on it together.

What do you think?

**Comment by zemirco** [comment]
Sounds reasonable. Never used haproxy though but I'm sure we'll find a good default config together. Mozilla has a great [config generator](https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy-1.5.14&openssl=1.0.1e&hsts=yes&profile=modern).

Didn't know about version 2.0 already using haproxy. That means we would replace stud with haproxy only for version < 2.0, right?

**Comment by klaemo** [comment]
Yes, for the time being it's only relevant for 1.x. I'm not sure if 2.0 will ship with haproxy, but their dev cluster uses it.

Mozilla's configs are awesome :)

I'm not so sure about haproxy anymore after doing some research:

- it doesn't support http2 (https://istlsfastyet.com/#server-performance)
- you have to manually update its OCSP stapling data :-/ (https://kura.io/2014/07/02/haproxy-ocsp-stapling/)

Maybe nginx is the better option after all? I've been using it in production in front of CouchDB for several years...so there's that :D

**Comment by zemirco** [comment]
Alright, I'll start working on a first implementation with nginx.

**Comment by zemirco** [comment]
It works https://github.com/zemirco/couchdb-ssl.

I just have to get the permissions right. Maybe you could help me with that. Then I'll create a proper pull request and we can switch to nginx.

**Comment by zemirco** [comment]
Updated `nginx.conf` with ocsp enabled and hsts disabled. Also used the official nginx installation from their dockerfile.

Logging now also works as expected.

**Comment by klaemo** [comment]
\o/ :tada: 

Looks great. If you want to open a PR, go ahead :) We only need to update the Readme accordingly.

**Comment by klaemo** [comment]
I added you as a collaborator, so in the future you can just push changes directly. I'd just a appreciate a heads up for bigger changes. :)

**Comment by zemirco** [comment]
Thank you! Nevertheless I created a pull request so you can give your final go.
