### ISSUE TITLE
License for image?

### ISSUE THREAD

**Issue by konrad-2013** [klaemo/docker-couchdb-ssl#9]
Hi,
I really like your image and would like to use it at work, but without a license attached this is impossible. Could you please add a license, e.g. Apache, which allows commercial usage as well?

Thanks in advance

**Comment by klaemo** [comment]
Thanks for reporting this. I added the Apache License :)

@zemirco I hope you're okay with that?! :)

**Comment by zemirco** [comment]
yeah sure :+1:

**Comment by konrad-2013** [comment]
Great, thanks guys :-)
